--- !train_config  # Default config's train config

number_of_epochs: null
batch_size: null
weights: null

optimizer: !optimizer
    optimizer: "ADAM"  # "ADAM" / "RMSPROP" / "SGD"
    learning_rate: null
    learning_rate_schedule: !learning_rate_schedule
        type: "CONSTANT"  # "CONSTANT" / "CYCLIC" / "STEP_DECAY" / "EXPONENTIAL_DECAY"
        decay_steps: null
        decay_rate: null
        cycle_length: null
        cycle_length_increase: 2.0
        initial_value_decrease: 1.0
    momentum: 0.0
    beta_1: 0.9
    beta_2: 0.999
    epsilon: 0.0000001
    rho: 0.9
    amsgrad: false
    nesterov: false
    centered: false

regularizer_config: !regularizer_config
    use_regularizer: false
    regularizer: null  # "L1" / "L2"
    lambda_coefficient: null
    normalize: false
    filter_regex: null